### ISSUE TITLE
Use settings

### ISSUE THREAD

**Issue by f2prateek** [segment-integrations/analytics-android-integration-moengage#1]
@Atrix1987 I noticed that the integration doesn't actually the settings defined here https://cloudup.com/c3_JIfjV27L

**Comment by Atrix1987** [comment]
We get it in a different way @f2prateek, manifest meta. So the settings in segment are kind of irrelevant

**Comment by f2prateek** [comment]
@Atrix1987 The point of using segment is that additional code is not required. If users have to add extra lines to even initialize the integration, that defeats the purpose of using Segment. It's not always possible in all cases, but for something as basic as initializing the SDK, we should not require extra code, especially since we're asking them to enter it in the Segment app.

We have other tools that do grab information from the manifest as well, but still provide a programatic way of providing settings.

**Comment by Atrix1987** [comment]
will change to using settings in the next release. Will keep this as an open issue till then. But @f2prateek I did not receive any update on the new release process.

**Comment by f2prateek** [comment]
Segment will still be making releases to MoEngage for now. Once we can polish the process with a few partners I was going to reach out to you with next steps. Or we can transfer it to you now if you'd prefer. Let me know and I can let you know what is involved.

**Comment by moeNandi** [comment]
@f2prateek can you share the details with us. You can send an email to abhishek@moengage.com

**Comment by moeNandi** [comment]
Closed with the PR #2
