### ISSUE TITLE
Toast Message shown in every activity [Screenshot attached]

### ISSUE THREAD

**Issue by rjhashlearn** [segment-integrations/analytics-android-integration-moengage#4]
![img_save_v2](https://cloud.githubusercontent.com/assets/15018392/14664427/69f2d4fc-06e8-11e6-818c-31fae7e66f59.jpg)

Read in this[ thread ](https://github.com/segmentio/analytics-android/issues/384#issue) that onPause logs can be ignored and they don't affect functionality. 

But its quite misleading when distributing the debug build for internal testing team. Is there someway this can be suppressed to only show in logs and not as a toast message ?

**Comment by f2prateek** [comment]
@rjhashlearn This would be better suited to ask MoEngage directly, since the toast message doesn't come from the integration.

**Comment by rjhashlearn** [comment]
@f2prateek Thanks. Checked with MoEnage team and got this reply 

> This has been fixed in latest MoEngage SDK.But Segment has not released the latest MoEngage SDK hence you are seeing the toast messages.

**Comment by f2prateek** [comment]
Thanks! I can make a release for this integration (the MoEngage version on master is 6.0.33).

**Comment by umangmoe** [comment]
@f2prateek the latest version is 6.0.13 not 6.0.33. Currently this repo is using 6.0.03. Will give you a pull request for the update by tomorrow morning. Please go ahead with the release after that.

**Comment by rjhashlearn** [comment]
@f2prateek From the conversation I had with MoEngage team, the current segment integration has MoEngage SDK v5.3.10 and not 6.0.33 . I'm unaware of your workflow but can it happen that the master branch is updated but a release is not made for it ?

**Comment by prashant74** [comment]
@f2prateek I have upgraded MoEngage SDK version to 6.0.13 and have raised the pull request as well.
You can merge the pull request and go ahead with release
